language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: ZLZ2/Sd8h3dXsk0sb1eo2e7ff80/o/smV2XDYnL7C6GRa3xw/cpWptF0XSaGFzujieuJQOZmmqAoxvxObIt9RLyWRf5Tbf7kjwMcViEgSa2llcA4H5tbKEiGUWmPAwNOA8zQfmW9JktpISHplzg0l+Bn76Wwt43BurH5O45z9Mcey4VOUac7kPeQCT50yJYyPx7rrTislPd8tTDWo+ilNyiOiTLxjzfNaxvshOuRLlLmtUXo/KY4ImeKfs111X38kr9EyLZLAT+LdnaLeYCVk/NP4xvA7fZkQMXaCreEmvTVW91ynBz2s86XEjTg1cBSv9yv48fwlHycqagI6eERY5wQZQ9P3AUJoELjuGnO/e9AqqH02xR0GkigBxCuyUyvwBZOoA+ApZ+teaP7z8HeQgzc73imrKEMF2gcFxz6HluB2xieGeDeU5aD/CO22BzE+d5/ARtuFGdFUfuv7k2KjFgHRTFGLLIJM//9f2exyg8HDXmMdsQ0qvVdAfqNxk0W4iu1H1YUCHZgQnXmj4QxDR86Wa/16JYNQP0LynGC9+LvbwCPq5YZyoUc2B7GnR8ocjjXXXeVLuR8PIRJ+1boOQ+Sjx6MoS6XXEgdf9CZRdl7VuTuis4dPCGkgZCDLkqkUUriWsvTDh0ROiWnOA8udYkdgWe5BBGAK1vtazZ96ns=
  - secure: cKxpYU15/0VAyS3PjbPyCqbEeGAUMHtvZhMrdZfbtOndZvo2kkFnlqMbfKLN58lk1MGyrKTSpUin6TxiFSnq9YCVvEloObGSP5htPudjDWzELuAnsf6o8EfEjKY2Zd7gf53pZ8S/g5v947ugl2h4IPE4ZRNmpbGoFTOWC+SBzV+nK+QzdBlHh8CJuFcFlZyH2jI+R+BFpUokY1LyaIpH65WfxMCarhoP/SSmuI3r5b3xySZev0so50NJ0ZumDY735pdA4pfgmjAZ4vE9bSnaznZFYkZ2LGP2fn0WfX6H8DGK4/fKuG6xpldwBKt3M1C2zSko/ecgMKAHg3culZKi/4W+iWtbOnorwkPMpFjQSBFcruNCTtFSB91fV8r90SKjabecIb8vZ8EweIOigriVJkHuTKGnzXFagohTaGFn24mH5Ludr2aGrIiC/XWIRqWNSLjZqI42dE5kecRPlE2O6NSyculdXf+wzBG2PP/UvdxCRTnzSpGDDvWd9yAthc34zRZXPd3RPl8iLyG72eypsJm8kiWlwBwk5aPxMVOYvnxffvt+kBrf5Z8vdhCy94sxa32zWl7q7FfF3o8ifoHE9nD1/qDNcKxlTA2X+GxPuw/VmBpDmpbIabWIdYshGGQEx5GB9QsulKs7Iz7hSu5nCNvSmvviTvlOUkia6Xuey14=
  - secure: qczyIZl7He/Hh5TwFkMUwSnyYwB/b1XCQXG2PnDJWfLkRVZ8+UAnl0yt05b7pMXKeJ0UfaglSzcvXI2++UcNVkjZoGRp/9HuKgqafzBjrDyLh/6rdbmZyIE4tj9txCnGglu/bQWMJ407UtRtzwx5mGXsCNBjYbfMYwoePmSeK3BeTg7kV9Wsx7+jqHcrczywapMDGh8v+HY7P8i2jw67dBdHP6B4HgnKdvt1SuHzJ0WMp73u4jb/kQu4vHKIZaKadYmq5htKhcD/zXkd4v6veO4Cp6esT9kmNFFeqdoJRbNX/khzG3VzDqbnX/6Z1+8ruJv8WnOUlRhaJDox77t7fTu0Qq7gbFG0/zf56a/JMjE4+KKyD7W+EY1hVrZQ8n+l5C8lrVRHu7tc19x72ruXhem/RyBf/8PtFCr9+GuJy2uSg2SANnE1xWJFe+xgEgenXYI07g01sE8GDLFm4p59sWn818aHrtqoEuoLTK0WDSPLz+Hv9orpTuNFGkYsAdlnpjlswPXCLDicSSj37G5+Un/H+gbgU1efNYx8mL9BDRPYnO3XIex/mFh/sJnsv9oBXS0Wu4g1YJ3z/LHqBZSiUwMwOhEtvwyUeNIBPqVUO6YfYZH75CIxRg05Da899nJAyMG9flz9hoHhK1TrFbiqRCaWMqKH057UfGTKpVrHGOk=

services: postgresql
addons:
  postgresql: 9.4
install: mvn install checksum:files -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
- dropdb --if-exists sc_lint_test
- psql -c 'create database sc_lint_test;' -U postgres
cache:
  directories:
  - .autoconf
  - $HOME/.m2
script:
- mvn versioneye:update test jacoco:report
after_success:
- mvn coveralls:report
notifications:
  slack:
    secure: ar8mq3cXiZx7QehmtvDDAzGanJcL7KWrvbGzo8RGqFToVyVCqfaKaelmqv/TCLCOr8DssP3yKm0yoPX0kiypqqbXaCp3v6a/4k8LtS3az41dKkVjQnRQFc3zDb3FkVKFIfEK8Y/hOUrwcZvSydh9rIsJ/m3CgAQz5mBCny3Vh7r5sjCazUO8pjOTIEWd2AOSgoJvlwKaUHYYtonqmHhycxjtus1zHkDsvrvs8iPHVVKv9FUHmCy0aiXcOnUihftRGElUCA9yujwdHC//yMjetdYihmmErmPkgQFLIW0y/G+6aeZzR8zW5zFlU/oQZBE6bCp3FU856wJV+ohp5+PwBwbqSU9b6Fszs9mgNzZFcIirxouB9NE6qQ1p/tp0y82nFfOsyY6OggqWtRNFGT7hyX2qaF1cIzovaKk8HQQKCg3RzpbmssEqDy8mvsF4GP4ByozCogghqmtpGhu+NjSdMkAZIZgVbcZLjoIDVV2uxA+7vAXdUvhBce4bpetv7r0ddxpq4lY36RANCJvbVQvsFtffJHd0j1cY7ipN3WdS7r7UmlqsKBcv+RiSVbKxhhjDk73jcMFBbkjDMHkIkSGLXmYxzqmHusDVwmprju835ae3RQyJ50RC8Zcj9pUZOUmoYCH7YGJuoLF7KIPbZzEcjxjwPFpa1WH6haSB/phzjgg=
deploy:
  provider: releases
  api_key:
    secure: ZfPAAfcU13jvUVRFRj6cp2OnDYWDVreLc8+QFApKeiApFuDOprZmmIk+HA34UbflJvXq0q9IWcvjS7nJIMGGMLH6vdFaPDLiKqjRVKPnyj10Q3XfEA/8ZRzMg5QpUf32GRrBemKzDkU5mdXhacYKb1cNCYsQt2Ix1DC6slwKmS2duOyLu/Knw25b/m7yz4KxDI+l7bjYwa3OIOEQxh0z5OcQpwt6Wy39iuc4pRLORrjtHGISOA+1PA+ycmBjZZGibNCZ0CRl5+f5AfdY1W3evaCg/7I3ha8Y+p/3MyTBVjISEefDTMkI+gWFncsHP4MP53w5Ekp0f7GovLAFOF7dqY3DF4Qkeyd6qHHIsDHRr3Zyp/JD5iAQtezW45oy/afsRiherBBUbwppb/63IYbBSu69wJZAupY3tycSgpO/KCQ+giV/NzhzspNbevsCsaNWbt3a0DPqvVYVWmRGhU2PjNUy21WslvIQT2lUzMWRM11ubkF4MFfH1OLrBP4LinNG2FZ5pKd3kBldePInieQ89xfuFnQ2jqtfGI+lTWNEhcgOBMAs57s6mCLDu4xvyDWclD3DRvlhKWKe6iaYoLnkRW2ko4IlP4ksCQatCPzSa06Kg4ax8vhyDKA4CpcAqUsYKY80OV9xjQqabuz4N+fxCi0e3sY7QVuYLrwfKbhVBxo=
  file: 
  - target/schemacrawler-additional-lints-${TRAVIS_TAG}.jar
  - target/schemacrawler-additional-lints-${TRAVIS_TAG}.jar.md5
  - target/schemacrawler-additional-lints-${TRAVIS_TAG}.jar.sha1
  skip_cleanup: true
  on:
    tags: true
    repo: mbarre/schemacrawler-additional-lints
branches:
  except:
  - travis