language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: pYTnADdShGADib2I83d37Q/0HWbNvQQ5slALZkE6uFHxt3xQB+iNg65VWhJZqobobuIw7IO+/81oMrjEfrluH9niL8P5FrtKJFKZhzgMXfXm+3ScLrIeRg/sFIBahqPBZcZ2hAXSeOgMCz0zDpwmnvWpvLqNmHa54+ydevombqxPpAhJNdCWLhos+FypS7WzZ6z5mofGBxckSN+X9tdvLXQ1WXXIqTIzAdA7hh2tQacCDsVP4F7rJ7P7cGTLUP0pCaBf2xWWj0p+v+EAZnbyGSi5t6EtF0KtGBfI6aFFzsdDvQU7b7YK6+ePRHLnAmLrGJLZl3YToa+xkDouvNKC9HMqKv1votZejnTmSxZlx87RVzl+i9AWF0RuOsrHmpC0+Ut25j7U4Vz+ZhCKX1ZqOMmt0JVxSQpZwL36SitvibN3UytLeVzp6K3hzO/1377SgLMNcJFkMy4eiwQ2MLFQQiG2KWCrnmecTuBmE/nWXKWBxY5l+gosY6u10ewk8lgfP/CQ8mKa5fHoz4qok7k4WcdpBTQ77uI0QJLgGSgLUbV0HUSNLZHlLC+jvxfm8IKp9jwU5PMvOxrS9lczKRDvvZ6xutMnlhcAkNMoTrv/vEqebF2CQwps9GPsgu4Zr7TyNpTRXD6ACSkXnpPmI3VUFZr7eI8dXm7pctc85gGIOt4=
  - secure: FA+iaibXX10y+o6eVErpHK74/xFvXKTm+vN9wwK11rUMxCHQI1kGXi4HuXGHiAHq15OFxKBJE3KVFjgzgLt3e33gh3Xq+jS0VHBkByKD7s/WMIlhzLWu47M8dtws3pQ9/sYQLLbOes+IyeGMHO0Q+rmFToXI6ca0gGyKsHPRbSHBDeSfcDQrp4r9n7hxxhTNsTsBW7B1dE0VZXEUTes7Cm+kCaaiPZ7KNlDn7U1otad8MajBTttAaVgeolKQcWoOhF6YINOUJW9C/tojX0Nwhw5OSJwKjPLk+a4MNx9anto56OrTbAGAGtZcxq2WBRpu2pyd+B+yLXFvp2f0USKXgKeAi7tn6PwH1UaExsI2UMvHKdRS7sFw5J1Eopi/uV7avTGZ9jxeICNeipnHsjEHCG95d3aPv+MeyNv0NC0VmMoSe7T5mTn5M4FxcW7AqNWiMgSK16YN1qzI3L4m3nCSmjvxDrB3uFCVD6LuaroGVcLY8Svpb8XN/A+Uvyos/8tUa+HqHG/4XU9aSacu21mZ/bMorKx/q+nXjqSTLCw4k2qNpm/zVD9/JFPcJwy5aBsFzu6/5AuvYik5G1YM0r8oPi4XRZsLOTi9+2dCThcPUXccVQkXGlspj0f9X18gHh+2qXBAMoEJ0gw4Jx9KyN6oXHqYrAUXeS5DAVc1K0fR1A4=
  - secure: IKGjvz0nqWm0DxwPOnHU6sLWpbIvHS9mRNg7PMwQsMhq9sT1KvWhCyUuCKTDn7uSRz7ZVvi/vI4hXE11BEssIT37dX6PMC2hBKsnfs0S3X5VwKzlJ7+fjrjGpPPVqIageYgFRWIhed1WouLxN67ZS4RXja3QhK1dcFVoZZxx8BD5yB5cNWw9EHT03oR1FpmNCIbH63dZqoO4hW5GapwP3d62hbniW67IeIBlO9VoTjTrlpcDMdKKujBO2fmYgn1ztlIiM3rkaq/L9PsPapatdfUbD3e0dhENN0haZn9RPEox5cS09LC7oKYfZB9zo8Ox8t+7WZAY3YDKqxLjtZUOu+ft7Bt/Y3/PMzI7DEbrq10JQmU7/rI4ceeWtmSnzevxFTtEVBTEJUkr58y6F7BQF3RNnDeqY5EPdR/0Zcm9UgQGGZQ2SUOSL01cRVyQE1SEGQIcG65pNu9hFsYlv31U3Bv5WULlGgtFk24IJHWpcY2Ffnj8K7Sjlezm5Lhj9nAkAWbKl6uoV36MNEotECwVGuNkVQPoGr+1s3zuY0Slx+4z/G47Mp0xRqLhwEL+VD3UXP0XxX6ex9IOaxZlD658zqpGKa3NsXvBAnR1tWR78av3VsstzK/gSJkEc+T5SGoUWeyVJwMkr7ZMaY18z4pprEGWzzqikfbGVjkMac0cYkg=
services: postgresql
addons:
  postgresql: 9.4
before_script:
- dropdb --if-exists sc_lint_test
- psql -c 'create database sc_lint_test;' -U postgres
cache:
  directories:
  - .autoconf
  - $HOME/.m2
script:
- mvn versioneye:update test jacoco:report
after_success:
- mvn coveralls:report
notifications:
  slack:
    secure: ar8mq3cXiZx7QehmtvDDAzGanJcL7KWrvbGzo8RGqFToVyVCqfaKaelmqv/TCLCOr8DssP3yKm0yoPX0kiypqqbXaCp3v6a/4k8LtS3az41dKkVjQnRQFc3zDb3FkVKFIfEK8Y/hOUrwcZvSydh9rIsJ/m3CgAQz5mBCny3Vh7r5sjCazUO8pjOTIEWd2AOSgoJvlwKaUHYYtonqmHhycxjtus1zHkDsvrvs8iPHVVKv9FUHmCy0aiXcOnUihftRGElUCA9yujwdHC//yMjetdYihmmErmPkgQFLIW0y/G+6aeZzR8zW5zFlU/oQZBE6bCp3FU856wJV+ohp5+PwBwbqSU9b6Fszs9mgNzZFcIirxouB9NE6qQ1p/tp0y82nFfOsyY6OggqWtRNFGT7hyX2qaF1cIzovaKk8HQQKCg3RzpbmssEqDy8mvsF4GP4ByozCogghqmtpGhu+NjSdMkAZIZgVbcZLjoIDVV2uxA+7vAXdUvhBce4bpetv7r0ddxpq4lY36RANCJvbVQvsFtffJHd0j1cY7ipN3WdS7r7UmlqsKBcv+RiSVbKxhhjDk73jcMFBbkjDMHkIkSGLXmYxzqmHusDVwmprju835ae3RQyJ50RC8Zcj9pUZOUmoYCH7YGJuoLF7KIPbZzEcjxjwPFpa1WH6haSB/phzjgg=
deploy:
  provider: releases
  api_key:
    secure: ZfPAAfcU13jvUVRFRj6cp2OnDYWDVreLc8+QFApKeiApFuDOprZmmIk+HA34UbflJvXq0q9IWcvjS7nJIMGGMLH6vdFaPDLiKqjRVKPnyj10Q3XfEA/8ZRzMg5QpUf32GRrBemKzDkU5mdXhacYKb1cNCYsQt2Ix1DC6slwKmS2duOyLu/Knw25b/m7yz4KxDI+l7bjYwa3OIOEQxh0z5OcQpwt6Wy39iuc4pRLORrjtHGISOA+1PA+ycmBjZZGibNCZ0CRl5+f5AfdY1W3evaCg/7I3ha8Y+p/3MyTBVjISEefDTMkI+gWFncsHP4MP53w5Ekp0f7GovLAFOF7dqY3DF4Qkeyd6qHHIsDHRr3Zyp/JD5iAQtezW45oy/afsRiherBBUbwppb/63IYbBSu69wJZAupY3tycSgpO/KCQ+giV/NzhzspNbevsCsaNWbt3a0DPqvVYVWmRGhU2PjNUy21WslvIQT2lUzMWRM11ubkF4MFfH1OLrBP4LinNG2FZ5pKd3kBldePInieQ89xfuFnQ2jqtfGI+lTWNEhcgOBMAs57s6mCLDu4xvyDWclD3DRvlhKWKe6iaYoLnkRW2ko4IlP4ksCQatCPzSa06Kg4ax8vhyDKA4CpcAqUsYKY80OV9xjQqabuz4N+fxCi0e3sY7QVuYLrwfKbhVBxo=
  file: target/schemacrawler-additionnallints-${TRAVIS_TAG}.jar
  skip_cleanup: true
  on:
    tags: true
    repo: mbarre/schemacrawler-additionnallints
